import Vue from "vue";
import AngleDownSVG from "~/assets/svg/AngleDownSVG";
import AngleLeftSVG from "~/assets/svg/AngleLeftSVG";
import AngleRightSVG from "~/assets/svg/AngleRightSVG";
import ArrowRightSVG from "~/assets/svg/ArrowRightSVG";
import MarkSVG from "~/assets/svg/MarkSVG";
import PencilSVG from "~/assets/svg/PencilSVG";
import PlusSVG from "~/assets/svg/PlusSVG";
import TrashSVG from "~/assets/svg/TrashSVG";
import XSVG from "~/assets/svg/XSVG";
import CalendarSVG from "~/assets/svg/CalendarSVG";
import CarretDownSVG from "~/assets/svg/CarretDownSVG";
import LayersSVG from "~/assets/svg/LayersSVG";
import GraphSVG from "~/assets/svg/GraphSVG";
import ThreeSomeSVG from "~/assets/svg/ThreeSomeSVG";
import GearsSVG from "~/assets/svg/GearsSVG";
import EnvelopeSVG from "~/assets/svg/EnvelopeSVG";
import HeadPhonesSVG from "~/assets/svg/HeadPhonesSVG";
import HelpCenterSVG from "~/assets/svg/HelpCenterSVG";
import HomeSVG from "~/assets/svg/HomeSVG";
import PowerSVG from "~/assets/svg/PowerSVG";
import LogoSVG from "~/assets/svg/LogoSVG";
import InfoSVG from "~/assets/svg/InfoSVG";
import FieldsSVG from "~/assets/svg/FieldsSVG";
import Calendar2SVG from "~/assets/svg/Calendar2SVG";
import LogoCirclesSVG from "~/assets/svg/LogoCirclesSVG";
import CheckSVG from "~/assets/svg/CheckSVG";

Vue.component("AngleDownSVG", AngleDownSVG);
Vue.component("AngleLeftSVG", AngleLeftSVG);
Vue.component("AngleRightSVG", AngleRightSVG);
Vue.component("ArrowRightSVG", ArrowRightSVG);
Vue.component("MarkSVG", MarkSVG);
Vue.component("PencilSVG", PencilSVG);
Vue.component("PlusSVG", PlusSVG);
Vue.component("TrashSVG", TrashSVG);
Vue.component("XSVG", XSVG);
Vue.component("CalendarSVG", CalendarSVG);
Vue.component("CarretDownSVG", CarretDownSVG);
Vue.component("LayersSVG", LayersSVG);
Vue.component("GraphSVG", GraphSVG);
Vue.component("ThreeSomeSVG", ThreeSomeSVG);
Vue.component("GearsSVG", GearsSVG);
Vue.component("EnvelopeSVG", EnvelopeSVG);
Vue.component("HeadPhonesSVG", HeadPhonesSVG);
Vue.component("HelpCenterSVG", HelpCenterSVG);
Vue.component("HomeSVG", HomeSVG);
Vue.component("PowerSVG", PowerSVG);
Vue.component("LogoSVG", LogoSVG);
Vue.component("InfoSVG", InfoSVG);
Vue.component("FieldsSVG", FieldsSVG);
Vue.component("Calendar2SVG", Calendar2SVG);
Vue.component("LogoCirclesSVG", LogoCirclesSVG);
Vue.component("CheckSVG", CheckSVG);